server:
  port: 8010
spring:
  application:
    name: phclass-user-service
    #解决引入sentinel无法启动的问题（版本适配的造成的）
  main:
    allow-circular-references: true
  #nacos的地址
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.214.53:8848
    #sentinel注入
    sentinel:
      transport:
        #dashboard: 123.57.214.53:8080
        dashboard: 127.0.0.1:8080
        port: 9998
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.214.53/cloud_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Temp123456
  #在控制台打印sql语句
  zipkin:
    base-url: http://123.57.214.53:9411/ #zipkin地址
    discovery-client-enabled: false #不⽤开启服务发现
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #下划线转驼峰
    map-underscore-to-camel-case: true
#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
